# Generated by Django 4.0.2 on 2022-02-20 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Categories',
                'verbose_name_plural': 'Categories',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Poets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('year_of_life', models.CharField(db_index=True, max_length=255)),
                ('category_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='poetsofkazakhstan.categories')),
            ],
            options={
                'verbose_name': 'Poets',
                'verbose_name_plural': 'Poets',
            },
        ),
        migrations.CreateModel(
            name='Poems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('main', models.TextField(blank=True)),
                ('poet_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='poetsofkazakhstan.poets')),
            ],
        ),
    ]
