# Generated by Django 4.0.2 on 2022-02-20 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poetsofkazakhstan', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poems',
            options={'verbose_name': 'Poems', 'verbose_name_plural': 'Poems'},
        ),
    ]
