# Generated by Django 4.0.2 on 2022-02-21 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poetsofkazakhstan', '0002_alter_poems_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Informations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField(blank=True)),
                ('info_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='poetsofkazakhstan.poets')),
            ],
            options={
                'verbose_name': 'Informations',
                'verbose_name_plural': 'Informations',
            },
        ),
        migrations.AddField(
            model_name='poets',
            name='info_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='poetsofkazakhstan.informations'),
        ),
    ]
