# Generated by Django 4.0.2 on 2022-02-21 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poetsofkazakhstan', '0003_informations_poets_info_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informations',
            name='info_id',
        ),
    ]
