# Generated by Django 4.0.2 on 2022-02-22 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poetsofkazakhstan', '0005_informations_info_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
